[package]
name = "imgname"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
filetime = "0.2"
kamadak-exif = "0.5.4"